---
schema:
  procedures: {}
  tables:
    columns:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - column_id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - view_id
          match_type: ''
          name: columns_fk_view_id
          on_delete: CASCADE
          on_update: CASCADE
          options: []
          reference_fields:
            - view_id
          reference_table: views
          type: FOREIGN KEY
      fields:
        column_id:
          data_type: integer
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: column_id
          order: 1
          size:
            - 0
        column_order:
          data_type: integer
          default_value: 0
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: column_order
          order: 8
          size:
            - 0
        column_sort:
          data_type: enum
          default_value: ticket_id_asc
          extra:
            list:
              - ticket_id_asc
              - ticket_id_desc
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: column_sort
          order: 7
          size:
            - 0
        drop_action:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: drop_action
          order: 6
          size:
            - 0
        name:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: name
          order: 5
          size:
            - 0
        rt_query:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: rt_query
          order: 4
          size:
            - 0
        type:
          data_type: enum
          default_value: ~
          extra:
            list:
              - rt
              - custom
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: type
          order: 3
          size:
            - 0
        view_id:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: view_id
          order: 2
          size:
            - 0
      indices:
        - fields:
            - view_id
          name: columns_idx_view_id
          options: []
          type: NORMAL
      name: columns
      options: []
      order: 1
    users:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - user_id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - rt_username
          match_type: ''
          name: rt_username
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
      fields:
        avatar_url:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: avatar_url
          order: 5
          size:
            - 0
        first_name:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: first_name
          order: 3
          size:
            - 0
        last_name:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: last_name
          order: 4
          size:
            - 0
        role:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: role
          order: 6
          size:
            - 0
        rt_username:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: rt_username
          order: 2
          size:
            - 255
        user_id:
          data_type: integer
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: user_id
          order: 1
          size:
            - 0
      indices: []
      name: users
      options: []
      order: 2
    views:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - view_id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - user_id
          match_type: ''
          name: views_fk_user_id
          on_delete: CASCADE
          on_update: CASCADE
          options: []
          reference_fields:
            - user_id
          reference_table: users
          type: FOREIGN KEY
      fields:
        extra:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: extra
          order: 4
          size:
            - 0
        name:
          data_type: text
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: name
          order: 3
          size:
            - 0
        user_id:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: user_id
          order: 2
          size:
            - 0
        view_id:
          data_type: integer
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: view_id
          order: 1
          size:
            - 0
      indices:
        - fields:
            - user_id
          name: views_idx_user_id
          options: []
          type: NORMAL
      name: views
      options: []
      order: 3
  triggers: {}
  views: {}
translator:
  add_drop_table: 0
  filename: ~
  no_comments: 0
  parser_args:
    sources:
      - Column
      - User
      - View
  parser_type: SQL::Translator::Parser::DBIx::Class
  producer_args: {}
  producer_type: SQL::Translator::Producer::YAML
  show_warnings: 0
  trace: 0
  version: 0.11021
